AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-financial-dashboard

  Sample SAM Template for serverless-financial-dashboard

Parameters:
  InvestmentTableName:
    Type: String
    Description: Name of the DynamoDB table that stores investments.
    Default: investment

Globals:
  Function:
    Timeout: 3

Resources:
  InvestmentApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: InvestmentApi
      StageName: Prod
      Cors:
        AllowOrigin: "'http://192.168.31.194:3000'"
        AllowCredentials: true
        AllowMethods: "'POST,GET,DELETE,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,X-CSRF-TOKEN'"

  InvestmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: investment/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          INVESTMENT_TABLE_NAME: !Ref InvestmentTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InvestmentTableName
      Events:
        GetAllInvestments:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi  # 引用共享的 API
            Path: /investment
            Method: get
        GetInvestmentById:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment/{id}
            Method: get
        CreateInvestment:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment
            Method: post
        UpdateInvestmentById:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment/{id}
            Method: put
        DeleteInvestmentById:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment/{id}
            Method: delete

Outputs:
  InvestmentApi:
    Description: "API Gateway endpoint URL for investment-related operations"
    Value: !Sub "https://${InvestmentApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/investment/"
  InvestmentFunction:
    Description: "Lambda Function ARN for investment-related operations"
    Value: !GetAtt InvestmentFunction.Arn
  InvestmentFunctionIamRole:
    Description: "Implicit IAM Role created for InvestmentFunction"
    Value: !GetAtt InvestmentFunctionRole.Arn
