AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-financial-dashboard
  
  Production-ready serverless API for investment management using AWS Lambda and DynamoDB

Parameters:
  InvestmentTableName:
    Type: String
    Description: Name of the DynamoDB table that stores investments
    Default: investment
  
  Environment:
    Type: String
    Description: Deployment environment (dev, prod)
    Default: prod
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        INVESTMENT_TABLE_NAME: !Ref InvestmentTableName
        ENVIRONMENT: !Ref Environment

Resources:
  InvestmentApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: InvestmentApi
      StageName: !If [IsProd, Prod, !Ref Environment]
      Cors:
        AllowOrigin: "'*'"
        AllowCredentials: false
        AllowMethods: "'POST,GET,DELETE,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,X-CSRF-TOKEN'"

  InvestmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/investment.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InvestmentTableName
      Events:
        GetAllInvestments:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment
            Method: get
        GetInvestmentById:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment/{id}
            Method: get
        CreateInvestment:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment
            Method: post
        UpdateInvestmentById:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment/{id}
            Method: put
        DeleteInvestmentById:
          Type: Api
          Properties:
            RestApiId: !Ref InvestmentApi
            Path: /investment/{id}
            Method: delete

Outputs:
  InvestmentApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${InvestmentApi}.execute-api.${AWS::Region}.amazonaws.com/${InvestmentApi.Stage}/investment/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  
  InvestmentFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt InvestmentFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"
